<?php

namespace FondOfSpryker\Yves\GoogleTagManager\Plugin\VariableBuilder\DefaultVariables;

use Codeception\Test\Unit;
use FondOfSpryker\Yves\GoogleTagManager\GoogleTagManagerFactory;
use Spryker\Shared\Kernel\Store;

class CurrencyVariableBuilderPluginTest extends Unit
{
    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\GoogleTagManagerFactory|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $factoryMock;

    /**
     * @var \Spryker\Shared\Kernel\Store|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $storeMock;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Plugin\VariableBuilder\DefaultVariables\CurrencyVariableBuilderPlugin
     */
    protected $plugin;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->factoryMock = $this->createMock(GoogleTagManagerFactory::class);
        $this->storeMock = $this->createMock(Store::class);

        $this->plugin = new CurrencyVariableBuilderPlugin();
        $this->plugin->setFactory($this->factoryMock);
    }

    /**
     * @return void
     */
    public function testHandleSuccess(): void
    {
        $this->factoryMock->expects($this->atLeastOnce())
            ->method('getStore')
            ->willReturn($this->storeMock);

        $this->storeMock->expects($this->atLeastOnce())
            ->method('getCurrencyIsoCode')
            ->willReturn('EUR');

        $array = $this->plugin->handle([]);

        $this->assertArrayHasKey('currency', $array);
        $this->assertEquals('EUR', $array['currency']);
    }
}
