<?php


namespace FondOfSpryker\Yves\GoogleTagManager\Plugin\VariableBuilder\DefaultVariables;

use Codeception\Test\Unit;
use FondOfSpryker\Yves\GoogleTagManager\GoogleTagManagerFactory;
use Spryker\Shared\Kernel\Store;

class StoreNameVariableBuilderPluginTest extends Unit
{
    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\GoogleTagManagerFactory|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $factoryMock;

    /**
     * @var \Spryker\Shared\Kernel\Store|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $storeMock;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Plugin\VariableBuilder\DefaultVariables\StoreNameVariableBuilderPlugin
     */
    protected $plugin;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->factoryMock = $this->createMock(GoogleTagManagerFactory::class);
        $this->storeMock = $this->createMock(Store::class);

        $this->plugin = new StoreNameVariableBuilderPlugin();
        $this->plugin->setFactory($this->factoryMock);
    }

    /**
     * @return void
     */
    public function testHandleSuccess(): void
    {
        $this->factoryMock->expects($this->atLeastOnce())
            ->method('getStore')
            ->willReturn($this->storeMock);

        $this->storeMock->expects($this->atLeastOnce())
            ->method('getStoreName')
            ->willReturn('STORE_NAME');

        $array = $this->plugin->handle([]);

        $this->assertArrayHasKey('store', $array);
        $this->assertEquals('STORE_NAME', $array['store']);
    }
}
