<?php

namespace FondOfSpryker\Yves\GoogleTagManager\Plugin\VariableBuilder\NewsletterVariables;

use FondOfSpryker\Yves\GoogleTagManager\Plugin\VariableBuilder\DefaultVariables\DefaultFieldVariableBuilderPluginInterface;

interface NewsletterVariablesPluginInterfaceField extends DefaultFieldVariableBuilderPluginInterface
{
}
