<?php

namespace FondOfSpryker\Yves\GoogleTagManager\Twig;

use Codeception\Test\Unit;
use FondOfSpryker\Yves\GoogleTagManager\Plugin\EnhancedEcommerce\EnhancedEcommercePageTypePluginInterface;
use Symfony\Component\HttpFoundation\Request;
use Twig_Environment;

class EnhancedEcommerceTwigExtensionTest extends Unit
{
    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Twig\EnhancedEcommerceTwigExtension
     */
    protected $twigExtension;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Plugin\EnhancedEcommerce\EnhancedEcommercePageTypePluginInterface[]|\PHPUnit\Framework\MockObject\MockObject[]
     */
    protected $enhancedEcommercePageTypePluginInterfaceCollection;

    /**
     * @var \Twig_Environment|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $twigEnvironmentMock;

    /**
     * @var \Symfony\Component\HttpFoundation\Request|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $requestMock;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $enhancedEcommercePageTypePluginInterface = $this->getMockBuilder(EnhancedEcommercePageTypePluginInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $enhancedEcommercePageTypePluginInterface->method('handle')
            ->willReturn('template');

        $this->twigEnvironmentMock = $this->getMockBuilder(Twig_Environment::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->requestMock = $this->getMockBuilder(Request::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->enhancedEcommercePageTypePluginInterfaceCollection = [
            'productDetail' => $enhancedEcommercePageTypePluginInterface,
        ];

        $this->twigExtension = new EnhancedEcommerceTwigExtension($this->enhancedEcommercePageTypePluginInterfaceCollection);
    }

    /**
     * @return void
     */
    public function testGetFunctionsSuccess(): void
    {
        $result = $this->twigExtension->getFunctions();

        $this->assertIsArray($result);
        $this->assertNotCount(0, $result);
    }

    /**
     * @return void
     */
    public function testRenderEnhancedEcommerceSuccess(): void
    {
        $result = $this->twigExtension->renderEnhancedEcommerce($this->twigEnvironmentMock, 'productDetail', $this->requestMock);

        $this->assertEquals('template', $result);
    }

    /**
     * @return void
     */
    public function testRenderEnhancedEcommerceFailure(): void
    {
        $result = $this->twigExtension->renderEnhancedEcommerce($this->twigEnvironmentMock, 'no_plugin', $this->requestMock);

        $this->assertEquals('', $result);
    }
}
