<?php

namespace FondOfSpryker\Yves\GoogleTagManager\Twig;

use Codeception\Test\Unit;
use FondOfSpryker\Yves\GoogleTagManager\Dependency\Client\GoogleTagManagerToCartClientInterface;
use FondOfSpryker\Yves\GoogleTagManager\Dependency\Client\GoogleTagManagerToSessionClientInterface;
use FondOfSpryker\Yves\GoogleTagManager\Model\DataLayer\DefaultVariableBuilder;
use FondOfSpryker\Yves\GoogleTagManager\Model\DataLayer\ProductVariableBuilder;
use Twig_Environment;

class GoogleTagManagerTwigExtensionTest extends Unit
{
    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Dependency\Client\GoogleTagManagerToCartClientInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $googleTagManagerToCartClientMock;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Dependency\Client\GoogleTagManagerToSessionClientInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $googleTagManagerToSessionClientMock;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Dependency\Client\GoogleTagManagerToSessionClientInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $variableBuildersCollectionMock;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Model\DataLayer\DefaultVariableBuilder|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $defaultVariableBuilderMock;

    /**
     * @var \FondOfSpryker\Yves\GoogleTagManager\Model\DataLayer\ProductVariableBuilder|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $productDetailVariableBuilderMock;

    /**
     * @var \Twig_Environment|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $twigEnvironmentMock;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->googleTagManagerToCartClientMock = $this->getMockBuilder(GoogleTagManagerToCartClientInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->googleTagManagerToSessionClientMock = $this->getMockBuilder(GoogleTagManagerToSessionClientInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->twigEnvironmentMock = $this->getMockBuilder(Twig_Environment::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->productDetailVariableBuilderMock = $this->getMockBuilder(ProductVariableBuilder::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->defaultVariableBuilderMock = $this->getMockBuilder(DefaultVariableBuilder::class)
            ->disableOriginalConstructor()
            ->getMock();
    }
}
